colours = {
    '0': 'white',
    '1': 'light_red',
    '2': 'light_yellow',
    '3': 'dark_orange',
    '4': 'green',
    '5': 'dodger_blue_2',
    '6': 'dark_magenta_2',  # 'purple_4a',
    '7': 'orange_4b',
    '8': 'black',
    '9': 'grey_62',
    'A': 'red_1',
    'B': 'dodger_blue_2',
    'C': 'gold_1',
    'D': 'green',
    'E': 'dark_orange_3b',
    'F': 'sandy_brown',
    'G': 'green_3a',
    'H': 'light_green',
    'I': 'dodger_blue_1',
    'J': 'deep_pink_3a',
    'K': 'green',
    'L': 'green_4',
    'M': 'turquoise_2',
    'N': 'sky_blue_1',
    'O': 'white',
    'R': 'turquoise_2',
    'U': 'dark_magenta_2',
    'V': 'dark_magenta_1',
    'Z': 'dark_orange',
}
